In [1]:
a = (2,3)
b = 

SyntaxError: invalid syntax (2961522966.py, line 2)

In [21]:
import cv2
import numpy as np
img = cv2.imread("inp1_forest.png")
# a = img.shape
# arr = np.zeros(a)
# b = (a[0]*2,a[1]*2)
# print(a)
# print(b)
# print(arr.shape)

p = img[0:3,1:6,0]
print(p)
p = [x for row in p for x in row ]
print(p)

[[199 199 199 191 191]
 [197 197 197 196 196]
 [196 196 196 196 196]]
[199, 199, 199, 191, 191, 197, 197, 197, 196, 196, 196, 196, 196, 196, 196]


In [6]:
for i in range(1,4):
    print(i)

1
2
3


In [12]:
from math import *
a = (2.2,24.54)
print(a)
a = (floor(a[0]),floor(a[1]))
print(a)

(2.2, 24.54)
(2, 24)


In [26]:
l = [1,2,3]
la = [4,5,6,"suraj",[0.2, 0.4]]
l.extend(la)
print(l)
print(len(l))

[1, 2, 3, 4, 5, 6, 'suraj', [0.2, 0.4]]
8


In [16]:
x = list(range(0,3))
y = list(range(4,8))
print(x)
print(y)
print(type(x))
[X,Y] = np.meshgrid(x,y)
X = X.astype(np.float32)
print(X)
print(Y)
print(type(X[0,0]))

[0, 1, 2]
[4, 5, 6, 7]
<class 'list'>
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]
<class 'numpy.float32'>


In [3]:

from pyflann import *
import pyflann
import numpy as np
# from scipy.spatial import distance
import scipy
dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
testset = np.array(
    [[1., 1, 1, 1, 1],
     [90, 90, 10, 10, 1]
     ])

a = testset[0]
b = dataset[0]
ssd = np.sum((a-b)**2)

def kneareset_neighbour_pyflann(patches_database, query_patches, k, distance_metric = 'euclidean'):
    
    pyflann.set_distance_type(distance_type='cs')
    flann = FLANN()
    k_idx, k_dist = flann.nn( patches_database, query_patches, k, algorithm="kmeans", branching=32, iterations=7, checks=16)
    
    return k_idx, k_dist


#Ref: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html
def kneareset_neighbour_scipy(patches_database, query_patches, k, distance_metric = 'euclidean'):
    Dist = scipy.spatial.distance.cdist(patches_database, query_patches, distance_metric)
    k_idx = np.argpartition(Dist, range(k), axis=0)[:k, :]
    k_dist = Dist[np.argpartition(Dist, range(k), axis=0)[:k, :], np.arange(Dist.shape[1])[None, :]]
    return k_idx.T, k_dist.T

NNs, Dist = kneareset_neighbour(dataset, testset, k=2, distance_metric = 'cosine')
print(NNs)
print(Dist)


print("\npyflann")
NNs, Dist = kneareset_neighbour_pyflann(dataset, testset, k=2, distance_metric = 'euclidean')
print(NNs)
print(Dist)

# print(result)

# print( dists)

# dataset = np.random.rand(10000, 128)
# testset = np.random.rand(1000, 128)
# flann = FLANN()
# result, dists = flann.nn(
#     dataset, testset, 5, algorithm="kmeans", branching=32, iterations=7, checks=16)
# print(result)
# print( dists)

[[0 1]
 [2 1]]
[[0.10557281 0.11526976]
 [0.01056123 0.14729308]]

pyflann
[[0 1]
 [2 1]]
[[  1.33333333  23.42424242]
 [ 16.38596491 132.1025641 ]]


In [136]:
from numpy.linalg import norm
a = testset[0]
b = dataset[0]
print(a,b)
ssd = np.sum((a-b)**2)
cosine_sim = np.dot(a,b)/(norm(a)*norm(b))
print(np.dot(a,b))
print(norm(a)*norm(b))
print(norm(a))
print("ssd  =",ssd)
print("cosine sim = ",1-cosine_sim)

[1. 1. 1. 1. 1.] [1. 1. 1. 2. 3.]
8.0
8.94427190999916
2.23606797749979
ssd  = 5.0
cosine sim =  0.10557280900008414


In [94]:

# import required libraries
import numpy as np
from numpy.linalg import norm
from math import *
# define two lists or array
A = np.array([1,1,1,1,1])
# A = A/5
B = np.array([1,1,1,2,3])
# B = B/5
print("A:", A)
print("B:", B)
 
# compute cosine similarity
cosine = np.dot(A,B)/(norm(A)*norm(B))
print(sqrt(cosine))

A: [1 1 1 1 1]
B: [1 1 1 2 3]
0.9457416090031758


In [95]:
from scipy.spatial import distance
XA=np.array([A,B])
XB=np.array([A])
distances = scipy.spatial.distance.cdist(XA, XB, 'cosine')
print(distances)
print(XA)

[[2.22044605e-16]
 [1.05572809e-01]]
[[1 1 1 1 1]
 [1 1 1 2 3]]


In [ ]:
Y = cdist(XA, XB, 'euclidean')


In [37]:
lst = [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ]
print(np.array(lst))
dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
print(dataset)

[[  1.   1.   1.   2.   3.]
 [ 10.  10.  10.   3.   2.]
 [100. 100.   2.  30.   1.]]
[[  1.   1.   1.   2.   3.]
 [ 10.  10.  10.   3.   2.]
 [100. 100.   2.  30.   1.]]


In [39]:
a = [1,2,3,43,5,6]
print(a[0:2])

[1, 2]


In [51]:
a = np.array([[1,2],[5,6]])
a = np.reshape(a,(-1))
print(a)
#np.append(a,np.array([1,2,3]))

[1 2 5 6]


In [43]:
a = exp(3)
print(a)

20.085536923187668


In [49]:
a = np.ones((4,))
b = np.ones((6,))
a = np.append(a,b)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [60]:
a = np.empty((3))
# newrow = [1, 2, 3]
# A = numpy.vstack([A, newrow])
for _ in range(3):
    a = np.vstack([a,np.array([1,2,3])])
print(len(a))
print(a)

4
[[4.9e-324 9.9e-324 1.5e-323]
 [1.0e+000 2.0e+000 3.0e+000]
 [1.0e+000 2.0e+000 3.0e+000]
 [1.0e+000 2.0e+000 3.0e+000]]


In [62]:
a = [4,5,6]
a = a-2
print(a)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [14]:
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KDTree
import numpy as np
from math import *
import scipy
from numpy.linalg import norm
import pyflann
from pyflann import *


def kneareset_neighbour_pyflann(patches_database, query_patches, k, distance_metric = 'euclidean'):
    
    pyflann.set_distance_type(distance_type=distance_metric)
    flann = FLANN()
    k_idx, k_dist = flann.nn( patches_database, query_patches, k, algorithm="kmeans", branching=32, iterations=7, checks=16)
    
    return k_idx, k_dist


#Ref: https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html
def kneareset_neighbour_scipy(patches_database, query_patches, k, distance_metric = 'euclidean'):
    Dist = scipy.spatial.distance.cdist(patches_database, query_patches, distance_metric)
    k_idx = np.argpartition(Dist, range(k), axis=0)[:k, :]
    k_dist = Dist[np.argpartition(Dist, range(k), axis=0)[:k, :], np.arange(Dist.shape[1])[None, :]]
    return k_idx.T, k_dist.T

def knnsearch_cosine(patches_db, input_patches_p,k):

    NNs = []
    Dist = []
    for i in range(len(input_patches_p)):
        patch = input_patches_p[i]
        patchdb_norm = np.linalg.norm(patches_db, axis=1)
        dot = np.dot(patches_db,patch)
        temp = dot / patchdb_norm
        temp = temp / np.linalg.norm(patch)
        temp = 1-temp

        min_index = np.argpartition(temp,k)
        min_index = min_index[:k]
        NNs.append(min_index)
        Dist.append(temp[min_index])
    NNs = np.array(NNs)
    Dist = np.array(Dist)
    return NNs,Dist

def knnsearch_scikit(patches_db, input_patches,k, custom_distance_metric):
    nbrs = NearestNeighbors(n_neighbors=k, algorithm='ball_tree', metric = custom_distance_metric).fit(patches_db)
    distances, indices = nbrs.kneighbors(input_patches)
    return indices, distances  #NNs,Dist

def knnsearch_scikit_kdtree(patches_db, input_patches,k, distance_metric = 'euclidean'):
    kdt = KDTree(patches_db, leaf_size=30, metric=distance_metric)
    distances, indices = kdt.query(input_patches, k=2, return_distance=True)
    return indices, distances  #NNs,Dist


dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
testset = np.array(
    [[1., 1, 1, 1, 1],
     [90, 90, 10, 10, 1]
     ])

def euclidean_distance(x,y):
    return sqrt(np.sum((x-y)**2))

def cosine_distance(x,y):
    return 1-(np.dot(x,y)/(norm(x)*norm(y)))
    



In [18]:
print("Euclidean:", knnsearch_scikit(dataset,testset,2,custom_distance_metric=euclidean_distance))
print("Euclidean:", kneareset_neighbour_scipy(dataset, testset, 2, distance_metric = 'euclidean') )
print("\nCosine:", knnsearch_scikit(dataset,testset,2,custom_distance_metric=cosine_distance))
print("Cosine:",knnsearch_cosine(dataset,testset,2))
print("Random:", knnsearch_scikit(dataset,testset,2,cosine_distance))


Euclidean: (array([[0, 1],
       [2, 1]]), array([[  2.23606798,  15.74801575],
       [ 25.76819745, 113.35784049]]))
Euclidean: (array([[0, 1],
       [2, 1]]), array([[  2.23606798,  15.74801575],
       [ 25.76819745, 113.35784049]]))

Cosine: (array([[0, 1],
       [2, 1]]), array([[0.10557281, 0.11526976],
       [0.01056123, 0.14729308]]))
Cosine: (array([[0, 1],
       [2, 1]]), array([[0.10557281, 0.11526976],
       [0.01056123, 0.14729308]]))
Random: (array([[0, 1],
       [2, 1]]), array([[0.10557281, 0.11526976],
       [0.01056123, 0.14729308]]))


In [1]:
def euclidean_distance(x,y):
    return sqrt(np.sum((x-y)**2))


def cosine_distance(x,y):
    return 1-(np.dot(x,y)/(norm(x)*norm(y)))

def knnsearch_scikit(patches_db, input_patches,k, custom_distance_metric):
    nbrs = NearestNeighbors(n_neighbors=k, algorithm='ball_tree', metric = custom_distance_metric).fit(patches_db)
    distances, indices = nbrs.kneighbors(input_patches)
    return indices, distances
print("Random:", knnsearch_scikit(dataset,testset,2,euclidean_distance))

NameError: name 'dataset' is not defined

In [9]:
import cv2
import numpy as np
img = cv2.imread("inp3_building_SR_paper_l1.png")
# print("before shape = ", img.shape)
# (h, w) = img.shape[:2]
# (cX, cY) = (w // 2, h // 2)
# M = cv2.getRotationMatrix2D((cX, cY), -180, 1.0)
# rotated = cv2.warpAffine(img, M, (w, h))
# cv2.imshow("Rotated by -180 Degrees", rotated)
# cv2.waitKey()
# cv2.destroyAllWindows()
# print("rotated shape = ",rotated.shape)


flip0 = cv2.flip(img,0)
flip1 = cv2.flip(img,1)
rotated90 = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
rotated180 = cv2.rotate(img, cv2.ROTATE_180)

print("flip0 shape = ", flip0.shape)
print("flip1 shape = ", flip1.shape)
print("rotated90 shape = ", rotated90.shape)
print("rotated180 shape = ", rotated180.shape)

flip0_back = cv2.flip(flip0,0)
flip1_back = cv2.flip(flip1,1)
rotated90_back = cv2.rotate(rotated90, cv2.ROTATE_90_COUNTERCLOCKWISE)
rotated180_back = cv2.rotate(rotated180, cv2.ROTATE_180)
cv2.imshow("hey",flip0_back)
cv2.imshow("hey2",flip1_back)
cv2.imshow("hey3",rotated90_back)
cv2.imshow("hey4",rotated180_back)
cv2.waitKey()
cv2.destroyAllWindows()
print("\nAFTER\n")
print("flip0 shape = ", flip0_back.shape)
print("flip1 shape = ", flip1_back.shape)
print("rotated90 shape = ", rotated90_back.shape)
print("rotated180 shape = ", rotated180_back.shape)


flip0_back = flip0_back.astype('int')
flip1_back = flip1_back.astype('int')
rotated90_back = rotated90_back.astype('int')
rotated180_back = rotated180_back.astype('int')

avg_img = (flip0_back + flip1_back + rotated90_back + rotated180_back)//4
avg_img = avg_img.astype('uint8')

cv2.imshow("avg image",avg_img)
cv2.waitKey()
cv2.destroyAllWindows()

# rotated90 = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
# rotated180 = cv2.rotate(src, cv2.ROTATE_180)
# rotated90_ = cv2.rotate(src, cv2.ROTATE_90_COUNTERCLOCKWISE)
# print("rotated shape = ",rotated90.shape)
# cv2.imshow("hey",rotated90)
# cv2.waitKey()
# cv2.destroyAllWindows()

flip0 shape =  (262, 484, 3)
flip1 shape =  (262, 484, 3)
rotated90 shape =  (484, 262, 3)
rotated180 shape =  (262, 484, 3)

AFTER

flip0 shape =  (262, 484, 3)
flip1 shape =  (262, 484, 3)
rotated90 shape =  (262, 484, 3)
rotated180 shape =  (262, 484, 3)
[[[  3 201 101]
  [  2 201 102]
  [  1 201 102]
  [  2 201 101]
  [  2 201 101]]

 [[  0 199 100]
  [233 198  99]
  [240 199  99]
  [240 199 100]
  [ 22 199 100]]

 [[231 199 100]
  [253 198  99]
  [254 198 100]
  [255 198 100]
  [233 199 100]]

 [[255 198 101]
  [255 198 100]
  [254 198 101]
  [253 199 101]
  [253 198 101]]

 [[254 198 102]
  [254 198 102]
  [255 198 102]
  [254 198 102]
  [253 199 101]]]
[[[  3 201 101]
  [  2 201 102]
  [  1 201 102]
  [  2 201 101]
  [  2 201 101]]

 [[  0 199 100]
  [233 198  99]
  [240 199  99]
  [240 199 100]
  [ 22 199 100]]

 [[231 199 100]
  [253 198  99]
  [254 198 100]
  [255 198 100]
  [233 199 100]]

 [[255 198 101]
  [255 198 100]
  [254 198 101]
  [253 199 101]
  [253 198 101]]

 [[2

In [ ]:
a = []

In [9]:
import sklearn
valid_metrics = sorted(sklearn.neighbors.VALID_METRICS['ball_tree'])


['braycurtis',
 'canberra',
 'chebyshev',
 'cityblock',
 'dice',
 'euclidean',
 'hamming',
 'haversine',
 'infinity',
 'jaccard',
 'kulsinski',
 'l1',
 'l2',
 'mahalanobis',
 'manhattan',
 'matching',
 'minkowski',
 'p',
 'pyfunc',
 'rogerstanimoto',
 'russellrao',
 'seuclidean',
 'sokalmichener',
 'sokalsneath',
 'wminkowski']

In [93]:
from math import *
from numpy.linalg import norm
dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
testset = np.array(
    [[1., 1, 1, 1, 1],
     [90, 90, 10, 10, 1]
     ])
a = testset[0]
b = dataset[1]
print("custom dist matric = ",cosine_distance(a,b))
ssd = sqrt(np.sum((a-b)**2))
cosine_sim = np.dot(a,b)/(norm(a)*norm(b))
print(np.dot(a,b))
print(norm(a)*norm(b))
print(norm(a))
print("ssd  =",ssd)
print("cosine sim = ",1-cosine_sim)


def distance(p1,p2):
    sigma = np.std(p2)
    if(sigma==0):
        sigma = MIN_STD
    ssd =np.sum( np.sum((p1-p2)**2))
    dist = exp(-ssd/sigma)
    print(ssd)
    print(sigma)
    print(dist)
    return dist
print(distance(a,b))

custom dist matric =  0.11526975646027227
35.0
39.56008088970496
2.23606797749979
ssd  = 15.748015748023622
cosine sim =  0.11526975646027227
248.0
3.687817782917155
6.2283463615791535e-30
6.2283463615791535e-30


In [61]:
a,b =  knnsearch_new2(dataset,testset,k=2,distance_metric = 'cosine')
# a = np.array(a)
# b = np.array(b)
print("a = ",a)
print("b = ",b)

ValueError: Unrecognized metric 'cosine'

In [64]:
import numpy as np
from sklearn.metrics import pairwise_distances
from sklearn.metrics.pairwise import pairwise_kernels
X = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
Y = np.array(
    [[1., 1, 1, 1, 1],
     [90, 90, 10, 10, 1]
     ])
print(pairwise_distances(X, Y, metric='manhattan'))
# array([[ 4.,  2.],
#        [ 7.,  5.],
#        [12., 10.]])
print( pairwise_distances(X, metric='manhattan'))
# array([[0., 3., 8.],
#        [3., 0., 5.],
#        [8., 5., 0.]])
print( pairwise_kernels(X, Y, metric='cosine'))
# array([[ 2.,  7.],
#        [ 3., 11.],
#        [ 5., 18.]])

[[  3. 197.]
 [ 30. 168.]
 [228.  48.]]
[[  0.  29. 229.]
 [ 29.   0. 216.]
 [229. 216.   0.]]
[[0.89442719 0.41579996]
 [0.88473024 0.85270692]
 [0.72068558 0.98943877]]


In [44]:
from math import *
from numpy.linalg import norm
a = testset[1]
b = dataset[1]
print(a,b)
ssd = sqrt(np.sum((a-b)**2))
cosine_sim = np.dot(a,b)/(norm(a)*norm(b))
print(np.dot(a,b))
print(norm(a)*norm(b))
print(norm(a))
print("ssd  =",ssd)
print("cosine sim = ",1-cosine_sim)

[90. 90. 10. 10.  1.] [10. 10. 10.  3.  2.]
1932.0
2265.7257115546886
128.06638903318856
ssd  = 113.35784048754634
cosine sim =  0.14729307693899707


In [7]:
dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
testset = np.array(
    [[1., 1, 1, 1, 1],
     [90, 90, 10, 10, 1]
     ])

print(dataset*testset[1])

[[9.e+01 9.e+01 1.e+01 2.e+01 3.e+00]
 [9.e+02 9.e+02 1.e+02 3.e+01 2.e+00]
 [9.e+03 9.e+03 2.e+01 3.e+02 1.e+00]]
