In [1]:
a = (2,3)
b = 

SyntaxError: invalid syntax (2961522966.py, line 2)

In [21]:
import cv2
import numpy as np
img = cv2.imread("inp1_forest.png")
# a = img.shape
# arr = np.zeros(a)
# b = (a[0]*2,a[1]*2)
# print(a)
# print(b)
# print(arr.shape)

p = img[0:3,1:6,0]
print(p)
p = [x for row in p for x in row ]
print(p)

[[199 199 199 191 191]
 [197 197 197 196 196]
 [196 196 196 196 196]]
[199, 199, 199, 191, 191, 197, 197, 197, 196, 196, 196, 196, 196, 196, 196]


In [6]:
for i in range(1,4):
    print(i)

1
2
3


In [12]:
from math import *
a = (2.2,24.54)
print(a)
a = (floor(a[0]),floor(a[1]))
print(a)

(2.2, 24.54)
(2, 24)


In [26]:
l = [1,2,3]
la = [4,5,6,"suraj",[0.2, 0.4]]
l.extend(la)
print(l)
print(len(l))

[1, 2, 3, 4, 5, 6, 'suraj', [0.2, 0.4]]
8


In [16]:
x = list(range(0,3))
y = list(range(4,8))
print(x)
print(y)
print(type(x))
[X,Y] = np.meshgrid(x,y)
X = X.astype(np.float32)
print(X)
print(Y)
print(type(X[0,0]))

[0, 1, 2]
[4, 5, 6, 7]
<class 'list'>
[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]
<class 'numpy.float32'>


In [38]:
from pyflann import *
import numpy as np

dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
testset = np.array(
    [[1., 1, 1, 1, 1],
     [90, 90, 10, 10, 1]
     ])
flann = FLANN()
result, dists = flann.nn(
    dataset, testset, 2, algorithm="kmeans", branching=32, iterations=7, checks=16)
print(result)
print( dists)

# dataset = np.random.rand(10000, 128)
# testset = np.random.rand(1000, 128)
# flann = FLANN()
# result, dists = flann.nn(
#     dataset, testset, 5, algorithm="kmeans", branching=32, iterations=7, checks=16)
# print(result)
# print( dists)

[[0 1]
 [2 1]]
[[5.000e+00 2.480e+02]
 [6.640e+02 1.285e+04]]


In [37]:
lst = [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ]
print(np.array(lst))
dataset = np.array(
    [[1., 1, 1, 2, 3],
     [10, 10, 10, 3, 2],
     [100, 100, 2, 30, 1]
     ])
print(dataset)

[[  1.   1.   1.   2.   3.]
 [ 10.  10.  10.   3.   2.]
 [100. 100.   2.  30.   1.]]
[[  1.   1.   1.   2.   3.]
 [ 10.  10.  10.   3.   2.]
 [100. 100.   2.  30.   1.]]


In [39]:
a = [1,2,3,43,5,6]
print(a[0:2])

[1, 2]


In [51]:
a = np.array([[1,2],[5,6]])
a = np.reshape(a,(-1))
print(a)
#np.append(a,np.array([1,2,3]))

[1 2 5 6]


In [43]:
a = exp(3)
print(a)

20.085536923187668


In [49]:
a = np.ones((4,))
b = np.ones((6,))
a = np.append(a,b)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [60]:
a = np.empty((3))
# newrow = [1, 2, 3]
# A = numpy.vstack([A, newrow])
for _ in range(3):
    a = np.vstack([a,np.array([1,2,3])])
print(len(a))
print(a)

4
[[4.9e-324 9.9e-324 1.5e-323]
 [1.0e+000 2.0e+000 3.0e+000]
 [1.0e+000 2.0e+000 3.0e+000]
 [1.0e+000 2.0e+000 3.0e+000]]


In [ ]:
a = 